server:
  servlet:
    context-path: /server
  port: 8090
spring:
  redis:
    host: 192.168.32.137
    port: 6379
    password: 123456

mqtt-properties:
  host: tcp://192.168.11.163:1883
  clientId: Server
  username: mosquitto
  password:
  cleanSession: false
  connectionTimeout: 300
  keepAliveInterval: 60
  automaticReconnect: true
